services:
  # ─────────────── PostgreSQL для метаданных Superset ───────────────
  superset_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
    volumes:
      - superset_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      retries: 5

  # ─────────────── ClickHouse с данными банка ───────────────
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "9000:9000" # native protocol
      - "8123:8123" # HTTP protocol
    environment:
      CLICKHOUSE_USER: admin # имя пользователя
      CLICKHOUSE_PASSWORD: admin # пароль
      CLICKHOUSE_DB: bank # создаст БД bank при старте
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./data:/data # CSV‑файлы из хоста
    healthcheck:
      test: [ "CMD", "clickhouse-client", "--query", "SELECT 1" ]
      interval: 10s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - superset

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8088:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - superset
      - comments

  comments:
    build:
      context: ./infra/comments
    container_name: comments
    ports:
      - "8000:8000"
    volumes:
      - ./infra/comments/comments.db:/app/comments.db
    restart: unless-stopped

  # ─────────────── Одноразовый инициализатор Superset ───────────────
  superset_init:
    build: ./docker/superset # Dockerfile с clickhouse‑connect
    image: ghcr.io/aayurkov/bank-bi-superset/superset:${IMAGE_TAG:-latest}
    entrypoint: [ "/bin/bash", "/app/init_superset.sh" ]
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PWD: ${ADMIN_PWD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PWD}@superset_db:5432/${POSTGRES_DB}
    volumes:
      - ./infra/init_superset.sh:/app/init_superset.sh
      - superset_home:/app/superset_home
    depends_on:
      superset_db:
        condition: service_healthy
    restart: "no"

  # ─────────────── Основной веб‑сервер Superset ───────────────
  superset:
    build: ./docker/superset
    image: ghcr.io/aayurkov/bank-bi-superset/superset:${IMAGE_TAG:-latest}
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PWD}@superset_db:5432/${POSTGRES_DB}
      SUPERSET_LOAD_EXAMPLES: "no"
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      superset_init:
        condition: service_completed_successfully
      superset_db:
        condition: service_healthy
      clickhouse:
        condition: service_healthy

# ─────────────── Docker volumes ───────────────
volumes:
  superset_db_data:
  clickhouse_data:
  superset_home:
  grafana-storage:
