global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'superset'
    static_configs:
      - targets: ['superset:8088']

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:9000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']      