name: Build & Push Superset

on:
  push:
    branches: [ main ]
    paths:
      - "docker/superset/**"
      - ".github/workflows/build-push.yml"

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/superset

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write        # push в GHCR
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} ./docker/superset

      - name: Push image
        run: docker push $IMAGE_NAME:${{ github.sha }}

      # ───── Smoke‑test ─────
      - name: Run container & health‑check
        run: |
          docker run -d --name superset_test \
            -e SUPERSET_SECRET_KEY=test_key_123 \
            -p 18088:8088 $IMAGE_NAME:${{ github.sha }}
          for i in {1..20}; do
            sleep 5
            curl -fs http://localhost:18088/health && exit 0
          done
          echo "Superset health check failed" && docker logs superset_test && exit 1

      - name: Stop test container
        if: always()
        run: docker rm -f superset_test
